// AUTO-GENERATED by `ugly-app build:static` — do not edit.
// Regenerate with `ugly-app build:static` (also runs as part of `ugly-app build`).

export interface StaticAssetRecord {
  /** Full md5 of the file's bytes. */
  md5: string;
  /** R2 key — the public URL is this string with a leading slash. */
  key: string;
  bytes: number;
}

// `satisfies` (not `as const`) — it keeps the keys literal, which is what
// StaticAssetPath needs, while leaving the values mutable so the lookups below
// don't need a readonly-stripping cast.
export const staticAssets = {

} satisfies Record<string, StaticAssetRecord>;

/** Every path present in `static/` at build time. */
export type StaticAssetPath = never;

/**
 * Origin the assets are served from — the R2 bucket's custom domain, which
 * Cloudflare's CDN edge-caches directly. Empty means same-origin.
 */
export const staticBaseUrl = 'https://static.listentothiscrazypersontalkaboutstuff.xyz';

/**
 * Dev serves the files off disk from the vite middleware at same-origin, so an
 * asset you just added works before it has ever been published. Prod uses the
 * CDN origin. `import.meta.env` only exists under vite; the try/catch keeps
 * this module importable from Node and Workers, where prod is the right answer.
 */
function origin(): string {
  try {
    if ((import.meta as { env?: { DEV?: boolean } }).env?.DEV) return '';
  } catch {
    // no import.meta.env — not a vite context.
  }
  return staticBaseUrl;
}

/**
 * Content-addressed URL for a static asset. A typo or a deleted-but-still
 * referenced asset is a tsc error here, not a 404 in production.
 */
export function staticUrl(p: StaticAssetPath): string {
  return origin() + '/' + lookup(p)!.key;
}

/**
 * Escape hatch for runtime-computed names, e.g. `models/${name}.ugm`.
 * Returns null for an unknown path rather than building a URL that would 404.
 */
export function resolveStaticUrl(p: string): string | null {
  const rec = lookup(p);
  return rec ? origin() + '/' + rec.key : null;
}

/**
 * The value type says `| undefined` deliberately. Without it the `!` and the
 * truthiness check above are dead code in a project that does NOT enable
 * `noUncheckedIndexedAccess`, and `no-unnecessary-type-assertion` /
 * `no-unnecessary-condition` fail the lint gate on this generated file —
 * blocking the deploy of an app that never wrote it. With it, both reads are
 * honest under either compiler setting.
 */
function lookup(p: string): StaticAssetRecord | undefined {
  return (staticAssets as Record<string, StaticAssetRecord | undefined>)[p];
}
